version: '3.1'

services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
<<<<<<< HEAD
      MONGO_MOST: mongodb
=======
      MONGO_HOST: mongo
>>>>>>> 9e3595f (added bot)
      MONGO_USERNAME: root
      MONGO_PASSWORD: example

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    hostname: mongodb
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
<<<<<<< HEAD
      - 8081:8081
=======
      - 8080:8080
>>>>>>> 9e3595f (added bot)
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
<<<<<<< HEAD
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017/
=======
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
>>>>>>> 9e3595f (added bot)
